version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - helpdesk

  config-server:
    image: asborges/help-desk-config-server
    container_name: 'config-server'
    environment:
      - CONFIG_SERVER_URI=https://github.com/allansingi/help-desk-config-server.git
      - CONFIG_SERVER_USERNAME=allansingi
      - CONFIG_SERVER_PASSWORD=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
      - PORT=8888
    ports:
      - "8888:8888"
    expose:
      - 8888
    networks:
      - helpdesk

  service-discovery:
    image: asborges/help-desk-service-discovery
    container_name: 'service-discovery'
    environment:
      - CONFIG_SERVER_URI=config-server:8888
      - PORT=8761
    ports:
      - "8761:8761"
    expose:
      - 8761
    networks:
      - helpdesk
    depends_on:
      - config-server
    links:
      - config-server

networks:
  helpdesk:
    driver: bridge